### ISSUE TITLE
correct date in the ado file

### ISSUE THREAD

**Issue by ericmelse** [econcz/stata-arimaauto#1]
Dear Mr Bolotov,

After installing your latest update, running the `which `command, like:
```
which arimaauto
*! version 1.0.5  07oct2022  I I Bolotov
```
returns the version date of 07oct2022 whereas it should be 09feb2024.
I suppose it is a minor detail but it is helpful to users to be certain that the last installation of `arimaauto `is the current one.
Time permitting, you might want to update the ado file with the correct date.

Best regards,
Eric

**Comment by econcz** [comment]
Dear Sir, you're free to fork the code and make the change!
